export const ADDRESSES = [
  {
    email: "camila.abarca@mail.cl",
    label: "Casa Providencia",
    contactName: "Camila Abarca",
    contactPhone: "+56912341001",
    street: "Av. Providencia",
    number: "1921",
    apartment: "Depto 1202",
    commune: "Providencia",
    city: "Santiago",
    region: "RM",
    postalCode: "7500000",
    reference: "Frente a la plaza La Gloria",
    isDefault: false,
  },
  {
    email: "martin.calvo@mail.cl",
    label: "Oficina Vitacura",
    contactName: "Martín Calvo",
    contactPhone: "+56922332002",
    street: "Av. Kennedy",
    number: "5201",
    apartment: "Oficina 504",
    commune: "Vitacura",
    city: "Santiago",
    region: "RM",
    postalCode: "7630000",
    reference: "Acceso por puerta gris",
    isDefault: false,
  },
  {
    email: "valentina.cruz@mail.cl",
    label: "Depto Ñuñoa",
    contactName: "Valentina Cruz",
    contactPhone: "+56933443003",
    street: "Av. Irarrázaval",
    number: "3241",
    apartment: "Depto 6B",
    commune: "Ñuñoa",
    city: "Santiago",
    region: "RM",
    postalCode: "7750000",
    reference: "Entrada por pasillo rojo",
    isDefault: false,
  },
  {
    email: "lucas.herrera@mail.cl",
    label: "Casa Las Condes",
    contactName: "Lucas Herrera",
    contactPhone: "+56944554004",
    street: "Calle Los Militares",
    number: "2147",
    apartment: "Casa completa",
    commune: "Las Condes",
    city: "Santiago",
    region: "RM",
    postalCode: "7550000",
    reference: "Jardín trasero",
    isDefault: false,
  },
  {
    email: "isidora.vega@mail.cl",
    label: "Lo Barnechea",
    contactName: "Isidora Vega",
    contactPhone: "+56955665005",
    street: "Camino La Cumbre",
    number: "4020",
    apartment: "Casa 4",
    commune: "Lo Barnechea",
    city: "Santiago",
    region: "RM",
    postalCode: "7600000",
    reference: "Portón azul",
    isDefault: false,
  },
  {
    email: "diego.morales@mail.cl",
    label: "Depto Ñuñoa II",
    contactName: "Diego Morales",
    contactPhone: "+56966776006",
    street: "Calle Jorge Washington",
    number: "1802",
    apartment: "Depto 302",
    commune: "Ñuñoa",
    city: "Santiago",
    region: "RM",
    postalCode: "7780000",
    reference: "Segundo piso, lado norte",
    isDefault: false,
  },
  {
    email: "fernanda.lagos@mail.cl",
    label: "Depto Ñuñoa Sur",
    contactName: "Fernanda Lagos",
    contactPhone: "+56977887007",
    street: "Av. Grecia",
    number: "2901",
    apartment: "Depto 5C",
    commune: "Ñuñoa",
    city: "Santiago",
    region: "RM",
    postalCode: "7750000",
    reference: "Frente a Metro Grecia",
    isDefault: false,
  },
  {
    email: "julian.rios@mail.cl",
    label: "Casa La Reina",
    contactName: "Julián Ríos",
    contactPhone: "+56988998008",
    street: "Calle Santa Isabel",
    number: "1674",
    apartment: "Casa completa",
    commune: "La Reina",
    city: "Santiago",
    region: "RM",
    postalCode: "7800000",
    reference: "Sobre la esquina norte",
    isDefault: false,
  },
  {
    email: "camilo.saavedra@mail.cl",
    label: "Lo Barnechea Norte",
    contactName: "Camilo Saavedra",
    contactPhone: "+56999009009",
    street: "Camino El Alba",
    number: "5128",
    apartment: "Casa 2",
    commune: "Lo Barnechea",
    city: "Santiago",
    region: "RM",
    postalCode: "7610000",
    reference: "Portón blanco y ladrillo",
    isDefault: false,
  },
  {
    email: "renata.fuentes@mail.cl",
    label: "Depto Ñuñoa Norte",
    contactName: "Renata Fuentes",
    contactPhone: "+56910101010",
    street: "Av. Pedro de Valdivia",
    number: "2543",
    apartment: "Depto 701",
    commune: "Ñuñoa",
    city: "Santiago",
    region: "RM",
    postalCode: "7750000",
    reference: "Cerca de la estación Ñuñoa",
    isDefault: false,
  },
  {
    email: "paula.mendez@mail.cl",
    label: "Depto Providencia",
    contactName: "Paula Méndez",
    contactPhone: "+56911112011",
    street: "Antonio Varas",
    number: "1450",
    apartment: "Depto 804",
    commune: "Providencia",
    city: "Santiago",
    region: "RM",
    postalCode: "7500600",
    reference: "Torre norte, acceso por pasaje interior",
    isDefault: false,
  },
  {
    email: "sebastian.torres@mail.cl",
    label: "Casa Maipú",
    contactName: "Sebastián Torres",
    contactPhone: "+56922223012",
    street: "Av. El Rosal",
    number: "5221",
    apartment: "Casa 3",
    commune: "Maipú",
    city: "Santiago",
    region: "RM",
    postalCode: "9250000",
    reference: "Portón café, estacionamiento interior",
    isDefault: false,
  },
  {
    email: "carolina.pinto@mail.cl",
    label: "Depto La Reina",
    contactName: "Carolina Pinto",
    contactPhone: "+56933334013",
    street: "Av. Alcalde Fernando Castillo",
    number: "2735",
    apartment: "Depto 503",
    commune: "La Reina",
    city: "Santiago",
    region: "RM",
    postalCode: "7850000",
    reference: "Entrada por portón negro, torre B",
    isDefault: false,
  },
  {
    email: "ignacio.ruiz@mail.cl",
    label: "Depto Santiago Centro",
    contactName: "Ignacio Ruiz",
    contactPhone: "+56944445014",
    street: "Lord Cochrane",
    number: "1150",
    apartment: "Depto 1110",
    commune: "Santiago",
    city: "Santiago",
    region: "RM",
    postalCode: "8320000",
    reference: "Cerca del metro Toesca, torre sur",
    isDefault: true,
  },
];
