export const PRODUCTS = [
  {
    name: "Sofá Modular Arena",
    slug: "sofa-modular-arena",
    sku: "MOA-LIV-SOFA-001",
    price: 699990,
    stock: 6,
    description:
      "Módulos combinables, tapizado en lino tono arena; líneas suaves y cojines blandos.",
    imgUrl:
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?q=80&w=1600&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?q=80&w=1600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616593918824-4fef16054381?q=80&w=1600&auto=format&fit=crop",
    ],
    badge: ["destacado"],
    status: "activo",
    tags: ["living", "sofa", "modular", "lino"],
    material: "Estructura de madera seca y tapiz lino",
    color: "arena",
    dimensions: { height: 82, width: 220, length: 95, unit: "cm" },
    weight: { value: 48, unit: "kg" },
    fk_category_id: 1,
  },
  {
    name: "Velador Rústico",
    slug: "velador-rustico",
    sku: "MOA-DOR-VELA-002",
    price: 89990,
    stock: 10,
    description: "Velador compacto en madera envejecida con cajón oculto.",
    imgUrl:
      "https://images.unsplash.com/photo-1532372320572-cda25653a26d?q=80&w=1600&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1532372320572-cda25653a26d?q=80&w=1600&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: ["dormitorio", "velador", "madera"],
    material: "Madera reciclada",
    color: "nogal",
    dimensions: { height: 58, width: 45, length: 40, unit: "cm" },
    weight: { value: 14, unit: "kg" },
    fk_category_id: 3,
  },
  {
    name: "Mesilla Blanca + Acentos",
    slug: "mesilla-blanca-acentos-madera",
    sku: "MOA-DOR-MESA-003",
    price: 89990,
    stock: 16,
    description: "Mesilla lacada en blanco con detalles en roble natural.",
    imgUrl:
      "https://images.unsplash.com/photo-1499933374294-4584851497cc?q=80&w=1600&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1499933374294-4584851497cc?q=80&w=1600&auto=format&fit=crop",
    ],
    badge: ["nuevo"],
    status: "activo",
    tags: ["dormitorio", "mesilla", "minimal"],
    material: "MDF lacado y chapa roble",
    color: "blanco y roble",
    dimensions: { height: 60, width: 48, length: 38, unit: "cm" },
    weight: { value: 12, unit: "kg" },
    fk_category_id: 3,
  },
  {
    name: "Lámpara Colgante Globo Opal",
    slug: "lampara-colgante-globo-opal",
    sku: "MOA-ILU-COLG-001",
    price: 149990,
    stock: 12,
    description:
      "Luminaria colgante con difusor de vidrio opal y herrajes dorados.",
    imgUrl:
      "https://images.unsplash.com/photo-1600421684846-e7ebc943403b?q=80&w=1600&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1600421684846-e7ebc943403b?q=80&w=1600&auto=format&fit=crop",
    ],
    badge: ["destacado"],
    status: "activo",
    tags: ["iluminacion", "colgante", "vidrio"],
    material: "Vidrio opal y latón",
    color: "opal y dorado",
    dimensions: { height: 30, width: 30, length: 30, unit: "cm" },
    weight: { value: 4, unit: "kg" },
    fk_category_id: 4,
  },
  {
    name: "Lámpara de Mesa Textil Plisado",
    slug: "lampara-globo",
    sku: "MOA-ILU-MESA-002",
    price: 89990,
    stock: 15,
    description:
      "Base cerámica en tono crema con pantalla plisada de lino. Ideal para veladores o rincones de lectura.",
    imgUrl:
      "https://images.unsplash.com/photo-1579656618142-5192f72e2d3d?q=80&w=1600&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1579656618142-5192f72e2d3d?q=80&w=1600&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: ["iluminacion", "mesa", "textil"],
    material: "Cerámica y lino",
    color: "crema",
    dimensions: { height: 45, width: 25, length: 25, unit: "cm" },
    weight: { value: 3, unit: "kg" },
    fk_category_id: 4,
  },
  {
    name: "Escritorio Fresno",
    slug: "escritorio-fresno",
    sku: "MOA-OFI-ESCR-001",
    price: 249990,
    stock: 8,
    description:
      "Escritorio minimalista en fresno con superficie amplia y líneas limpias para home office.",
    imgUrl:
      "https://images.unsplash.com/photo-1646003607550-4b1b62e3a2d4?q=80&w=1600&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1646003607550-4b1b62e3a2d4?q=80&w=1600&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: ["oficina", "escritorio", "fresno"],
    material: "fresno",
    color: "madera clara",
    dimensions: { height: 75, width: 140, length: 70, unit: "cm" },
    weight: { value: 34, unit: "kg" },
    fk_category_id: 5,
  },
  {
    name: "Espejo Redondo Marco Madera",
    slug: "espejo-redondo-marco-madera",
    sku: "MOA-DEC-ESPE-001",
    price: 129990,
    stock: 9,
    description:
      "Espejo decorativo redondo con marco de madera natural y acabado mate.",
    imgUrl:
      "https://images.unsplash.com/photo-1598116132066-b730a4f8616a?q=80&w=1600&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1598116132066-b730a4f8616a?q=80&w=1600&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: ["decoracion", "espejo", "madera"],
    material: "Madera de fresno",
    color: "madera natural",
    dimensions: { height: 3, width: 90, length: 90, unit: "cm" },
    weight: { value: 8, unit: "kg" },
    fk_category_id: 6,
  },

  {
    name: "Bandeja Trenzada de Fibra Natural",
    slug: "bandeja-trenzada-fibra-natural",
    sku: "DEC-BANDEJAFI-001",
    price: 44990,
    stock: 18,
    description:
      "Bandeja decorativa hecha a mano en fibra natural con trenzado grueso. Ideal para servir o para organizar tazas, velas y accesorios sobre mesas o consolas.",
    imgUrl:
      "https://images.unsplash.com/photo-1600248384783-293685222ce4?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8NjZ8LXhCM3B6cHoyZzB8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=800",
    gallery: [
      "https://images.unsplash.com/photo-1600248384783-293685222ce4?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8NjZ8LXhCM3B6cHoyZzB8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=800",
    ],
    badge: [],
    status: "activo",
    tags: ["artesanal", "fibra natural", "organizadores", "decoración"],
    material: "Fibra natural",
    color: "fibra natural",
    fk_category_id: 6,
  },
  {
    name: "Librero Abierto Madera Clara",
    slug: "librero-abierto-madera-clara",
    sku: "LIV-LIBRERO-20111",
    price: 299990,
    stock: 7,
    description:
      "Librero abierto de líneas minimalistas en madera clara con repisas amplias para libros, cerámica y objetos decorativos. Ideal para sumar textura y altura en el living o la oficina.",
    imgUrl:
      "https://images.unsplash.com/photo-1724920190056-8746b87686b3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=685",
    gallery: [
      "https://images.unsplash.com/photo-1724920190056-8746b87686b3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=685",
    ],
    badge: [],
    status: "activo",
    tags: ["librero", "madera clara", "living", "almacenamiento abierto"],
    material: "Madera maciza",
    color: "madera clara",
    fk_category_id: 5,
  },
  {
    name: "Mesa Natural",
    slug: "mesa-natural-maciza",
    sku: "COM-MESARECT-20507",
    price: 749990,
    stock: 4,
    description:
      "Mesa rectangular en madera maciza con veta visible y acabado mate. Diseño contemporáneo de líneas rectas, ideal para espacios amplios y reuniones familiares.",
    imgUrl:
      "https://images.unsplash.com/photo-1611671107731-b7f49a23d416?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=922",
    gallery: [
      "https://images.unsplash.com/photo-1611671107731-b7f49a23d416?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=922",
    ],
    badge: [],
    status: "activo",
    tags: ["mesa", "madera natural", "comedor", "rectangular", "mesas-comedor"],
    material: "Madera maciza",
    color: "madera natural",
    fk_category_id: 2,
  },
  {
    name: "Mesa Rústica",
    slug: "mesa-rustica-reciclada",
    sku: "COM-MESARUST-20508",
    price: 649990,
    stock: 3,
    description:
      "Mesa de comedor artesanal elaborada en madera reciclada con acabado envejecido. Superficie robusta y patas gruesas que realzan el carácter natural del material.",
    imgUrl:
      "https://images.unsplash.com/photo-1628797285815-453c1d0d21e3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=774",
    gallery: [
      "https://images.unsplash.com/photo-1628797285815-453c1d0d21e3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=774",
    ],
    badge: [],
    status: "activo",
    tags: ["mesa", "rústica", "madera reciclada", "artesanal", "comedor"],
    material: "Madera reciclada",
    color: "madera envejecida",
    fk_category_id: 2,
  },
  {
    name: "Silla Lounge Madera y Rejilla Natural",
    slug: "silla-lounge-madera-rejilla-natural",
    sku: "LIV-SILLALOU-12001",
    price: 219990,
    stock: 8,
    description:
      "Silla lounge artesanal fabricada en madera clara con asiento y respaldo en rejilla natural. Su diseño de líneas limpias y estructura abierta la convierte en una pieza versátil, perfecta para espacios cálidos, naturales o estilo japandi.",
    imgUrl:
      "https://images.unsplash.com/photo-1741121893351-934936d1e97c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXw1NHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=900",
    gallery: [
      "https://images.unsplash.com/photo-1741121893351-934936d1e97c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXw1NHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=900",
    ],
    badge: [],
    status: "activo",
    tags: [
      "silla lounge",
      "madera clara",
      "rejilla natural",
      "artesanal",
      "living",
      "japandi",
      "minimalista",
    ],
    material: "Madera natural y rejilla tejida",
    color: "madera clara y beige natural",
    fk_category_id: 1,
  },
  {
    name: "Mesa de Centro Roble Natural",
    slug: "mesa-centro-roble-natural",
    sku: "LIV-MESACENT-13001",
    price: 189990,
    stock: 10,
    description:
      "Mesa de centro redonda en madera roble natural con base cruzada. Diseño escandinavo de líneas simples que aporta calidez y armonía visual al living. Ideal para acompañar sofás de tonos neutros.",
    imgUrl:
      "https://images.unsplash.com/photo-1721614463453-051bd28367b1?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwyN3x8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=700",
    gallery: [
      "https://images.unsplash.com/photo-1721614463453-051bd28367b1?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwyN3x8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=700",
    ],
    badge: [],
    status: "activo",
    tags: ["mesa de centro", "roble", "escandinavo", "living", "madera clara"],
    material: "Madera de roble natural",
    color: "madera clara natural",
    fk_category_id: 1,
  },
  {
    name: "Cama Tapizada Lino Beige",
    slug: "cama-tapizada-lino-beige",
    sku: "DOR-CAMALINO-31001",
    price: 899990,
    stock: 6,
    description:
      "Cama tapizada en lino beige con cabecera acolchada y estructura de madera. Su diseño minimalista y su paleta neutra aportan calidez y serenidad al dormitorio. Ideal para combinar con textiles suaves y accesorios naturales.",
    imgUrl:
      "https://images.unsplash.com/photo-1723468348842-589373089346?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXw2OHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=700",
    gallery: [
      "https://images.unsplash.com/photo-1723468348842-589373089346?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXw2OHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=700",
    ],
    badge: [],
    status: "activo",
    tags: [
      "cama",
      "dormitorio",
      "lino",
      "beige",
      "tapizado",
      "minimal",
      "nórdico",
    ],
    material: "Lino natural y madera de roble",
    color: "beige lino",
    fk_category_id: 3,
  },
  {
    name: "Librero Metálico Negro Minimal",
    slug: "librero-metalico-negro-minimal",
    sku: "LIV-LIBREROM-12002",
    price: 219990,
    stock: 7,
    description:
      "Librero abierto con estructura metálica negra y diseño minimalista. Ideal para organizar libros, cerámica o plantas, aportando ligereza visual y funcionalidad en espacios modernos.",
    imgUrl:
      "https://images.unsplash.com/photo-1758098491183-dc0d88e71322?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1758098491183-dc0d88e71322?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1758098492040-e3d0a38ab1bd?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1758098491112-3a00ea592c9c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: ["librero", "metal", "negro", "minimal", "living", "organización"],
    material: "Estructura metálica con acabado negro mate",
    color: "negro mate",
    fk_category_id: 1,
  },
  {
    name: "Escritorio Modular con Estantería",
    slug: "escritorio-modular-estanteria",
    sku: "HOM-ESCRIMOD-51001",
    price: 329990,
    stock: 5,
    description:
      "Escritorio modular con estructura metálica negra y repisas de madera natural. Su diseño vertical integra almacenamiento abierto y espacio de trabajo, ideal para oficinas modernas y livings funcionales.",
    imgUrl:
      "https://images.unsplash.com/photo-1737233433647-b53b339306f4?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1737233433647-b53b339306f4?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1737233504527-c5033f0f1430?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXw2NXx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: [
      "escritorio",
      "modular",
      "madera",
      "metal",
      "oficina",
      "estantería integrada",
    ],
    material: "Madera natural y estructura metálica negra",
    color: "madera clara y negro",
    fk_category_id: 5,
  },
  {
    name: "Silla Oficina Verde Oliva",
    slug: "silla-oficina-verde-oliva",
    sku: "HOM-SILLAOLV-52001",
    price: 149990,
    stock: 12,
    description:
      "Silla de oficina giratoria tapizada en tela verde oliva con base metálica cromada. Su diseño envolvente ofrece soporte lumbar y estilo contemporáneo, perfecta para espacios de trabajo modernos o estudios en casa.",
    imgUrl:
      "https://images.unsplash.com/photo-1713293309279-40a0451430eb?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXw5OXx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=700",
    gallery: [
      "https://images.unsplash.com/photo-1713293309279-40a0451430eb?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXw5OXx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=700",
    ],
    badge: [],
    status: "activo",
    tags: [
      "silla",
      "oficina",
      "ergonómica",
      "verde oliva",
      "moderna",
      "giratoria",
    ],
    material: "Tela tapizada y base metálica cromada",
    color: "verde oliva",
    fk_category_id: 5,
  },
  {
    name: "Lámpara de Mesa Cerámica Marfil",
    slug: "lampara-mesa-ceramica-marfil",
    sku: "ILU-LAMPACER-42001",
    price: 79990,
    stock: 14,
    description:
      "Lámpara de mesa con base de cerámica marfil texturizada y pantalla cónica de lino natural. Su diseño elegante y cálido complementa espacios de descanso y lectura con una luz suave y envolvente.",
    imgUrl:
      "https://images.unsplash.com/photo-1580130281320-0ef0754f2bf7?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxMjB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    gallery: [
      "https://images.unsplash.com/photo-1580130281320-0ef0754f2bf7?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxMjB8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    ],
    badge: [],
    status: "activo",
    tags: [
      "lámpara de mesa",
      "cerámica",
      "marfil",
      "iluminación",
      "pantalla lino",
      "decoración cálida",
    ],
    material: "Cerámica y lino natural",
    color: "marfil claro",
    fk_category_id: 4,
  },
  {
    name: "Lámpara Colgante Cobre Satinado",
    slug: "lampara-colgante-cobre-satinado",
    sku: "ILU-LAMPCOBR-41001",
    price: 119990,
    stock: 10,
    description:
      "Lámpara colgante de metal acabado cobre satinado con pantalla semiesférica. Aporta una iluminación cálida y direccional, ideal para comedores, cocinas o espacios de lectura. Su diseño limpio combina elegancia moderna y estilo industrial suave.",
    imgUrl:
      "https://images.unsplash.com/photo-1636368208791-17b81ed832d2?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxMjN8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    gallery: [
      "https://images.unsplash.com/photo-1636368208791-17b81ed832d2?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxMjN8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    ],
    badge: [],
    status: "activo",
    tags: [
      "lámpara colgante",
      "cobre",
      "satinado",
      "moderna",
      "industrial",
      "iluminación",
    ],
    material: "Metal con acabado cobre satinado",
    color: "cobre satinado",
    fk_category_id: 4,
  },
  {
    name: "Lámpara de Mesa Cobre Pulido",
    slug: "lampara-mesa-cobre-pulido",
    sku: "ILU-LAMPCOBP-42005",
    price: 89990,
    stock: 18,
    description:
      "Lámpara de mesa metálica con acabado en cobre pulido y brazo flexible orientable. Su diseño funcional y cálido la convierte en una pieza ideal para escritorios, veladores o rincones de lectura con estilo moderno.",
    imgUrl:
      "https://images.unsplash.com/photo-1542728928-1413d1894ed1?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1542728928-1413d1894ed1?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: [
      "lámpara de mesa",
      "cobre",
      "moderna",
      "metal",
      "iluminación",
      "orientable",
    ],
    material: "Metal con acabado cobre pulido",
    color: "cobre brillante",
    fk_category_id: 4,
  },
  {
    name: "Lámpara de Pie Cobre Envejecido",
    slug: "lampara-pie-cobre-envejecido",
    sku: "ILU-LAMPPIEC-43001",
    price: 149990,
    stock: 9,
    description:
      "Lámpara de pie de metal color cobre envejecido con brazo articulado y pantalla direccional. Ideal para rincones de lectura o livings, combina estética industrial con una calidez moderna.",
    imgUrl:
      "https://images.unsplash.com/photo-1607809714110-e34f71c7b2ed?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1607809714110-e34f71c7b2ed?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: [
      "lámpara de pie",
      "cobre envejecido",
      "industrial",
      "living",
      "lectura",
      "ajustable",
    ],
    material: "Metal acabado cobre envejecido",
    color: "cobre envejecido",
    fk_category_id: 4,
  },
  {
    name: "Sillón Madera Curvada Negro",
    slug: "sillon-madera-curvada-negro",
    sku: "LIV-SILLONC-12003",
    price: 179990,
    stock: 9,
    description:
      "Sillón de estructura en madera curvada con asiento y respaldo tapizados en tela negra. Su diseño ergonómico combina líneas escandinavas con un perfil liviano y contemporáneo, ideal para livings o rincones de lectura.",
    imgUrl:
      "https://images.unsplash.com/photo-1617364852223-75f57e78dc96?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxNTR8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    gallery: [
      "https://images.unsplash.com/photo-1617364852223-75f57e78dc96?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxNTR8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    ],
    badge: [],
    status: "activo",
    tags: [
      "sillón",
      "madera curvada",
      "tapizado negro",
      "ergonómico",
      "living",
      "escandinavo",
    ],
    material: "Madera curvada y tela tapizada",
    color: "madera natural y negro",
    fk_category_id: 1,
  },
  {
    name: "Silla Comedor Madera Vintage",
    slug: "silla-comedor-madera-vintage",
    sku: "COM-SILLAVIN-22002",
    price: 79990,
    stock: 14,
    description:
      "Silla de comedor fabricada en madera maciza con respaldo curvado y acabado natural. Su diseño clásico y atemporal combina la calidez artesanal con el confort moderno, ideal para comedores rústicos o estilo farmhouse.",
    imgUrl:
      "https://images.unsplash.com/photo-1583845112239-97ef1341b271?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxNjR8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    gallery: [
      "https://images.unsplash.com/photo-1583845112239-97ef1341b271?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxNjR8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    ],
    badge: [],
    status: "activo",
    tags: [
      "silla comedor",
      "madera natural",
      "rústico",
      "vintage",
      "farmhouse",
      "artesanal",
    ],
    material: "Madera maciza con acabado natural",
    color: "madera envejecida",
    fk_category_id: 2,
  },
  {
    name: "Set Decorativo Monocromo",
    slug: "set-decorativo-monocromo",
    sku: "DEC-SETMONO-62001",
    price: 69990,
    stock: 12,
    description:
      "Set decorativo de estilo contemporáneo compuesto por velas esculturales en blanco y negro, florero esférico en cerámica negra mate y libro decorativo de mesa. Aporta contraste y elegancia a livings o dormitorios de estética moderna.",
    imgUrl:
      "https://images.unsplash.com/photo-1663307257459-66c8766baa95?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxNzJ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    gallery: [
      "https://images.unsplash.com/photo-1663307257459-66c8766baa95?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxNzJ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=700",
    ],
    badge: [],
    status: "activo",
    tags: [
      "decoración",
      "velas",
      "florero negro",
      "monocromo",
      "moderno",
      "coffee table",
    ],
    material: "Cera, cerámica mate y papel decorativo",
    color: "blanco y negro",
    fk_category_id: 6,
  },
  {
    name: "Florero Cerámica Blanca con Espigas Secas",
    slug: "florero-ceramica-blanca-espigas-secas",
    sku: "DEC-FLORCERB-62002",
    price: 32990,
    stock: 20,
    description:
      "Florero de cerámica blanca con diseño acanalado y acabado brillante. Su composición aporta textura y luz a cualquier espacio, ideal para livings, comedores o dormitorios de estilo cálido y orgánico.",
    imgUrl:
      "https://images.unsplash.com/photo-1597385326493-bc600d15c39c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1597385326493-bc600d15c39c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1597385326531-bfbf6c51c800?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: [
      "florero",
      "cerámica blanca",
      "espigas secas",
      "decoración natural",
      "minimalista",
      "orgánico",
    ],
    material: "Cerámica esmaltada",
    color: "blanco y dorado trigo",
    fk_category_id: 6,
  },
  {
    name: "Velador Madera Natural",
    slug: "velador-madera-natural",
    sku: "DOR-VELAMAD-32001",
    price: 189990,
    stock: 8,
    description:
      "Velador fabricado en madera maciza con acabado natural, cajón superior y espacio abierto inferior para almacenamiento. Su diseño orgánico y cálido se integra fácilmente en dormitorios modernos o de estilo escandinavo.",
    imgUrl:
      "https://images.unsplash.com/photo-1646161249396-941393453032?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1646161249396-941393453032?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1649817018876-c05473c7e5a4?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDF8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop",
    ],
    badge: [],
    status: "activo",
    tags: [
      "velador",
      "madera natural",
      "dormitorio",
      "minimalista",
      "escandinavo",
      "moderno",
    ],
    material: "Madera maciza con acabado natural",
    color: "madera clara",
    fk_category_id: 3,
  },
  {
    name: "Lámpara de Escritorio Bronce Envejecido",
    slug: "lampara-escritorio-bronce-envejecido",
    sku: "ILU-LAMESBRO-42003",
    price: 74990,
    stock: 15,
    description:
      "Lámpara de escritorio articulada con estructura metálica en acabado bronce envejecido. Su diseño funcional y elegante combina estética vintage con practicidad moderna, ideal para escritorios, veladores o espacios de lectura.",
    imgUrl:
      "https://images.unsplash.com/photo-1733974352470-93abec47a814?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=627",
    gallery: [
      "https://images.unsplash.com/photo-1733974352470-93abec47a814?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=627",
    ],
    badge: [],
    status: "activo",
    tags: [
      "lámpara de escritorio",
      "bronce envejecido",
      "articulada",
      "iluminación moderna",
      "vintage",
      "oficina",
    ],
    material: "Metal con acabado bronce envejecido",
    color: "bronce oscuro",
    fk_category_id: 4,
  },
  {
    name: "Lámpara Opalina Blanca",
    slug: "lampara-opalina-blanca",
    sku: "ILU-LAMOPAL-42004",
    price: 65990,
    stock: 12,
    description:
      "Lámpara de mesa con base de cerámica blanca y pantalla esférica de vidrio opalino. Su luz cálida y difusa aporta serenidad y modernidad a cualquier ambiente, ideal para dormitorios o livings de estética minimalista.",
    imgUrl:
      "https://images.unsplash.com/photo-1733280881567-96f27a9a00ce?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDUyfHx8ZW58MHx8fHx8&auto=format&fit=crop&q=60&w=900",
    gallery: [
      "https://images.unsplash.com/photo-1733280881567-96f27a9a00ce?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDUyfHx8ZW58MHx8fHx8&auto=format&fit=crop&q=60&w=900",
    ],
    badge: [],
    status: "activo",
    tags: [
      "lámpara de mesa",
      "opalina",
      "blanca",
      "iluminación suave",
      "minimalista",
      "moderna",
    ],
    material: "Cerámica y vidrio opalino",
    color: "blanco cálido",
    fk_category_id: 4,
  },
  {
    name: "Lámpara de Pie Industrial Clara",
    slug: "lampara-pie-industrial-clara",
    sku: "ILU-LAMPIEIND-43001",
    price: 119990,
    stock: 7,
    description:
      "Lámpara de pie con estructura metálica en color negro y pantalla cilíndrica de vidrio transparente. Diseñada para destacar la bombilla tipo Edison, ofrece una iluminación cálida y ambiente contemporáneo con toques industriales.",
    imgUrl:
      "https://images.unsplash.com/photo-1579888028917-47462bb03ca9?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwyfHx8ZW58MHx8fHx8&auto=format&fit=crop&q=60&w=900",
    gallery: [
      "https://images.unsplash.com/photo-1579888028917-47462bb03ca9?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwyfHx8ZW58MHx8fHx8&auto=format&fit=crop&q=60&w=900",
    ],
    badge: [],
    status: "activo",
    tags: [
      "lámpara de pie",
      "industrial",
      "vidrio transparente",
      "negro",
      "Edison",
      "moderno",
    ],
    material: "Metal y vidrio",
    color: "negro con pantalla transparente",
    fk_category_id: 4,
  },
  {
    name: "Aplique Mural Dorado",
    slug: "aplique-mural-dorado-cepillado",
    sku: "ILU-APLIMURDOR-44001",
    price: 54990,
    stock: 10,
    description:
      "Aplique mural con acabado dorado cepillado y diseño cónico clásico. Ideal para destacar espacios de lectura, escritorios o dormitorios, aportando un toque cálido y sofisticado gracias a su luz dirigida y estética retro moderna.",
    imgUrl:
      "https://images.unsplash.com/photo-1697809462690-57bc1601f665?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwyMXx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=900",
    gallery: [
      "https://images.unsplash.com/photo-1697809462690-57bc1601f665?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwyMXx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=60&w=900",
    ],
    badge: [],
    status: "activo",
    tags: [
      "aplique mural",
      "dorado cepillado",
      "pared",
      "retro moderno",
      "iluminación de acento",
    ],
    material: "Metal acabado dorado cepillado",
    color: "dorado cálido",
    fk_category_id: 4,
  },
  {
    name: "Silla Cuero Caramelo",
    slug: "silla-oficina-cuero-caramelo",
    sku: "OFI-SILLACUERO-52002",
    price: 149990,
    stock: 9,
    description:
      "Silla de oficina tapizada en cuero sintético color caramelo con estructura ergonómica y base giratoria metálica negra. Ofrece comodidad y estilo, perfecta para escritorios modernos o espacios de trabajo en casa.",
    imgUrl:
      "https://images.unsplash.com/photo-1612372606404-0ab33e7187ee?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxMTJ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=900",
    gallery: [
      "https://images.unsplash.com/photo-1612372606404-0ab33e7187ee?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxMTJ8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=900",
    ],
    badge: [],
    status: "activo",
    tags: [
      "silla de oficina",
      "cuero caramelo",
      "ergonómica",
      "giratoria",
      "moderna",
      "home office",
    ],
    material: "Cuero sintético y metal",
    color: "caramelo y negro",
    fk_category_id: 5,
  },
  {
    name: "Dúo de Macetas",
    slug: "duo-macetas-follaje-verde",
    sku: "DEC-MACPAREJA-61001",
    price: 39990,
    stock: 14,
    description:
      "Set de dos macetas decorativas en madera natural. Su diseño minimalista y materiales nobles aportan frescura y equilibrio visual a cualquier espacio.",
    imgUrl:
      "https://images.unsplash.com/photo-1584589167171-541ce45f1eea?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxNDR8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=900",
    gallery: [
      "https://images.unsplash.com/photo-1584589167171-541ce45f1eea?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxib29rbWFya3MtcGFnZXwxNDR8fHxlbnwwfHx8fHw%3D&auto=format&fit=crop&q=60&w=900",
    ],
    badge: [],
    status: "activo",
    tags: [
      "macetas",
      "decoración natural",
      "madera",
      "plantas artificiales",
      "minimalista",
      "escandinavo",
      "japandi",
    ],
    material: "Madera natural y follaje sintético",
    color: "madera clara y verde hoja",
    fk_category_id: 6,
  },
  {
    name: "Mesa Redonda Escandinava",
    slug: "mesa-redonda-escandinava",
    sku: "COM-MESAREDES-21004",
    price: 359990,
    stock: 5,
    description:
      "Mesa de comedor redonda elaborada en madera natural con acabado mate. Su diseño escandinavo y proporciones equilibradas la hacen ideal para espacios luminosos y ambientes cálidos. Perfecta para reuniones cotidianas o comedores de estilo minimalista.",
    imgUrl:
      "https://images.unsplash.com/photo-1721742145236-d89b27b8ceb0?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDUzfHx8ZW58MHx8fHx8&auto=format&fit=crop&q=60&w=900",
    gallery: [
      "https://images.unsplash.com/photo-1721742145236-d89b27b8ceb0?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDUzfHx8ZW58MHx8fHx8&auto=format&fit=crop&q=60&w=900",
    ],
    badge: [],
    status: "activo",
    tags: [
      "mesa comedor",
      "madera natural",
      "escandinavo",
      "minimalista",
      "nórdico",
      "diseño cálido",
    ],
    material: "Madera natural con acabado mate",
    color: "madera clara",
    fk_category_id: 2,
  },
];
